# voyages:
#     path: /voyages
#     controller: App\Controller\VoyagesController::voyages

# voyagesName:
#   path: /voyages/{name}
#   controller: App\Controller\VoyagesController::voyagesName

# home:
#   path: /home
#   controller : App\Controller\HomeController::home


